{-# OPTIONS --safe --without-K --warning=noUserWarning --warning=noUselessPrivate --warning=noUnsupportedIndexedMatch #-}

open import Categories.Category using (Category)
open import Categories.Category.Monoidal using (Monoidal)
open import Categories.Category.Monoidal.Closed using (Closed)
open import Level using (0ℓ; _⊔_; lower)

module Categories.Rosen.Coherent.HigherMRS {o ℓ e} {C : Category o ℓ e} {M : Monoidal C} (Cl : Closed M) where

-- Higher-order (M,R)-systems following a Fibonacci-style construction:
-- each step A → B → [A,B] → [B,[A,B]] → ... embeds the two previous
-- levels into an internal hom.  Built as iterated IsoCommas of ⟅_⟆Φ and Vᵢ.
-- Exports: MRS3, 𝕄ℝ𝕊, 𝕄ℝ𝕊ₒ, Π-MRS, pℕ, 𝕄ℝ𝕊-F, 𝕄ℝ𝕊-down,
--          downF, MRS-chain, MRS∞, MRS∞-Obj, MRS∞-at,
--          MRS∞-proj, MRS∞-commute.

open import Data.Nat using (ℕ; zero; suc)
open import Data.Product using (Σ;_,_;proj₁;proj₂)
open import Relation.Binary.Core using (Rel)

open import Categories.Category.Construction.Arrow
open import Categories.Category.Construction.IsoComma using (IsoComma;IsoCommaObj;IsoComma⇒;ICproj₂)
open import Categories.Category.Instance.Cats using (Cats)
open import Categories.Functor using (Functor; _∘F_) renaming (id to idF)
open import Categories.Functor.Profunctor.Tabulator using (tab₀;tab⇒)
open import Categories.Morphism.Reasoning as MR
open import Categories.NaturalTransformation.NaturalIsomorphism as NI using (NaturalIsomorphism;niHelper; _ⓘʳ_; _ⓘᵥ_)
open import Categories.Rosen.Coherent.IdCore Cl
open import Categories.Rosen.Coherent.ProElements Cl {F = MRS-Profunctor}
open import Categories.Rosen.Coherent.Tabulator Cl using (⟅_⟆f)

import Reason
open Reason C
open MR

-- Arrow(C); see the note in Coherent/ProElements.agda.
module Arr = Categories.Category.Construction.Arrow C

-- MRS3: the 3rd level, IsoComma of ⟅_⟆Φ (from ProElements) and ⟅_⟆f (from Tabulator).
MRS3 : Category (o ⊔ ℓ ⊔ e) (o ⊔ ℓ ⊔ e) e
MRS3 = IsoComma ⟅_⟆Φ ⟅_⟆f

-- 𝕄ℝ𝕊 n: the n-th level category together with a functor to Arr.Arrow.
𝕄ℝ𝕊 : (n : ℕ) → Σ (Category (o ⊔ ℓ ⊔ e) (o ⊔ ℓ ⊔ e) e) (λ x → Functor x Arr.Arrow)
𝕄ℝ𝕊 zero = MRS3 , V₂
  where
    -- Base level: functor V₂ from MRS3 to Arr.Arrow.
    V₂ : Functor MRS3 Arr.Arrow
    V₂ = record
      { F₀ = λ x →
        let module x = IsoCommaObj x
        in record { arr = MR2.f (tab₀.ξ x.b) }
      ; F₁ = λ { {x} {y} f →
        let module x = IsoCommaObj x
            module y = IsoCommaObj y
            module f = IsoComma⇒ f
        in mor⇒ {dom⇒ = tab⇒.l f.g} {cod⇒ = tab⇒.r f.g}
          (let open Category.HomReasoning C in begin _ ≈⟨ sym-id-1 ○ assoc ⟩
                  _ ≈⟨ proj₁ (lower (tab⇒.eq f.g)) ⟩
                  _ ≈⟨ id-0 ⟩
                  _ ∎)}
      ; identity = Equiv.refl , Equiv.refl
      ; homomorphism = Equiv.refl , Equiv.refl
      ; F-resp-≈ = λ {(_ , dat) → (dat .proj₁) , (dat .proj₂)}
      }
𝕄ℝ𝕊 (suc n)
  = let MRSn = proj₂ (𝕄ℝ𝕊 n)
    in IsoComma ⟅_⟆Φ MRSn
  , (proj₂ (𝕄ℝ𝕊 n) ∘F ICproj₂)

-- 𝕄ℝ𝕊ₒ n: the n-th level category.
𝕄ℝ𝕊ₒ : (n : ℕ) → Category (o ⊔ ℓ ⊔ e) (o ⊔ ℓ ⊔ e) e
𝕄ℝ𝕊ₒ n = proj₁ (𝕄ℝ𝕊 n)

-- 𝕄ℝ𝕊ₐ n: the functor from the n-th level to Arr.Arrow.
-- 𝕄ℝ𝕊ₐ : (n : ℕ) → Functor (𝕄ℝ𝕊ₒ n) Arr.Arrow
-- 𝕄ℝ𝕊ₐ n = proj₂ (𝕄ℝ𝕊 n)

-- Π-MRS n: projection from level (suc n) down to level n.
Π-MRS : (n : ℕ) → Functor (𝕄ℝ𝕊ₒ (suc n)) (𝕄ℝ𝕊ₒ n)
Π-MRS n = ICproj₂

private module ArrC = Category Arr.Arrow
private module ArrMR = MR Arr.Arrow

V : (n : ℕ) → Functor (𝕄ℝ𝕊ₒ n) Arr.Arrow
V n = proj₂ (𝕄ℝ𝕊 n)

reduce : (k : ℕ) → Functor (𝕄ℝ𝕊ₒ k) (𝕄ℝ𝕊ₒ 0)
reduce 0 = idF
reduce (suc k) = reduce k ∘F Π-MRS k

VΠ : (k : ℕ) → NaturalIsomorphism (V k ∘F Π-MRS k) (V (suc k))
VΠ k = niHelper (record
  { η = λ X → ArrC.id {Functor.F₀ (V k) (Functor.F₀ (Π-MRS k) X)}
  ; η⁻¹ = λ X → ArrC.id {Functor.F₀ (V k) (Functor.F₀ (Π-MRS k) X)}
  ; commute = λ f → ArrMR.id-comm-sym {f = Functor.F₁ (V k ∘F Π-MRS k) f}
  ; iso = λ X → record { isoˡ = ArrC.identity² {Functor.F₀ (V k) (Functor.F₀ (Π-MRS k) X)} ; isoʳ = ArrC.identity² {Functor.F₀ (V k) (Functor.F₀ (Π-MRS k) X)} }
  })

reduce-compat : (k : ℕ) → NaturalIsomorphism (V 0 ∘F reduce k) (V k)
reduce-compat 0 = NI.unitorʳ
reduce-compat (suc k) =
  NI.trans (NI.sym-associator (Π-MRS k) (reduce k) (V 0)) (NI.trans
    ((reduce-compat k) ⓘʳ Π-MRS k)
    (VΠ k))

-- Paths in the chain are generated by identities, composition, and one-step
-- projections.  Keeping their syntax makes the associated downward functor
-- definitionally preserve composition; _≈′_ records the categorical laws
-- between path expressions.
data _≤′_ : Rel ℕ 0ℓ where
  ≤′-refl  : ∀ {n} → n ≤′ n
  ≤′-trans : ∀ {m n k} → m ≤′ n → n ≤′ k → m ≤′ k
  ≤′+1     : ∀ {n} → n ≤′ suc n


data _≈′_ : ∀ {n m} → (p q : n ≤′ m) → Set 0ℓ where
  ≈-assoc : ∀ {n m k l}
            (p : n ≤′ m) (q : m ≤′ k) (r : k ≤′ l) →
            ≤′-trans p (≤′-trans q r) ≈′ ≤′-trans (≤′-trans p q) r
  id-l : ∀ {n m} {p : n ≤′ m} → ≤′-trans ≤′-refl p ≈′ p
  id-r : ∀ {n m} {p : n ≤′ m} → ≤′-trans p ≤′-refl ≈′ p
  ≈′-refl : ∀ {n m} {p : n ≤′ m} → p ≈′ p
  ≤′-trans-cong : ∀ {n m k} {p q : n ≤′ m} {r s : m ≤′ k} →
                  p ≈′ q → r ≈′ s → ≤′-trans p r ≈′ ≤′-trans q s
  ≈′-trans : ∀ {n m} {p q r : n ≤′ m} → p ≈′ q → q ≈′ r → p ≈′ r
  ≈′-sym : ∀ {n m} {p q : n ≤′ m} → p ≈′ q → q ≈′ p

-- The free category generated by the one-step projections.  Its hom
-- equivalence exposes the exact path equation to MRS-chain.F-resp-≈, avoiding
-- any appeal to proof irrelevance under --without-K.
pℕ : Category 0ℓ 0ℓ 0ℓ
pℕ = record
  { Obj = ℕ
  ; _⇒_ = _≤′_
  ; _≈_ = _≈′_
  ; id = ≤′-refl
  ; _∘_ = λ q p → ≤′-trans p q
  ; assoc = ≈-assoc _ _ _
  ; sym-assoc = ≈′-sym (≈-assoc _ _ _)
  ; identityˡ = id-r
  ; identityʳ = id-l
  ; identity² = id-r
  ; equiv = record
    { refl = ≈′-refl
    ; sym = ≈′-sym
    ; trans = ≈′-trans
    }
  ; ∘-resp-≈ = λ q≈q′ p≈p′ → ≤′-trans-cong p≈p′ q≈q′
  }

𝕄ℝ𝕊-F : ∀ {n m} → m ≤′ n → Functor (𝕄ℝ𝕊ₒ n) (𝕄ℝ𝕊ₒ m)
𝕄ℝ𝕊-F ≤′-refl = idF
𝕄ℝ𝕊-F (≤′-trans p q) = 𝕄ℝ𝕊-F p ∘F 𝕄ℝ𝕊-F q
𝕄ℝ𝕊-F {suc n} {n} ≤′+1 = Π-MRS n

𝕄ℝ𝕊-η : ∀ {n m} (p : m ≤′ n) →
  NaturalIsomorphism (V m ∘F 𝕄ℝ𝕊-F p) (V n)
𝕄ℝ𝕊-η ≤′-refl = NI.unitorʳ
𝕄ℝ𝕊-η (≤′-trans {m} {x} {n} p q) =
  let θ = 𝕄ℝ𝕊-η {x} {m} p
      θ′ = 𝕄ℝ𝕊-η {n} {x} q
      first = 𝕄ℝ𝕊-F {x} {m} p
      second = 𝕄ℝ𝕊-F {n} {x} q
  in θ′ ⓘᵥ (θ ⓘʳ second) ⓘᵥ NI.sym-associator second first (V m)
𝕄ℝ𝕊-η {suc n} {n} ≤′+1 = VΠ n

-- A downward functor paired with its compatibility against V.
𝕄ℝ𝕊-down : ∀ {n m} (p : m ≤′ n) →
  Σ (Functor (𝕄ℝ𝕊ₒ n) (𝕄ℝ𝕊ₒ m))
    (λ F-down → NaturalIsomorphism (V m ∘F F-down) (V n))
𝕄ℝ𝕊-down p = 𝕄ℝ𝕊-F p , 𝕄ℝ𝕊-η p

downF : ∀ {n m} → m ≤′ n → Functor (𝕄ℝ𝕊ₒ n) (𝕄ℝ𝕊ₒ m)
downF p = proj₁ (𝕄ℝ𝕊-down p)

down-compat : ∀ {n m} (p : m ≤′ n) →
  NaturalIsomorphism (V m ∘F downF p) (V n)
down-compat p = proj₂ (𝕄ℝ𝕊-down p)

lemma-id : ∀ {n : ℕ} →
  NaturalIsomorphism (downF {n} {n} ≤′-refl) (idF {C = 𝕄ℝ𝕊ₒ n})
lemma-id = NI.refl

lemma-homomorphism : ∀ {n m k : ℕ} (m≤′n : m ≤′ n) (k≤′m : k ≤′ m) →
  NaturalIsomorphism (downF (≤′-trans k≤′m m≤′n))
    (downF k≤′m ∘F downF m≤′n)
lemma-homomorphism m≤′n k≤′m = NI.refl

lemma-Fresp : ∀ {n m : ℕ} {p q : m ≤′ n} → p ≈′ q →
  NaturalIsomorphism (downF p) (downF q)
lemma-Fresp (≈-assoc p q r) =
  NI.sym (NI.associator (downF r) (downF q) (downF p))
lemma-Fresp id-l = NI.unitorˡ
lemma-Fresp id-r = NI.unitorʳ
lemma-Fresp ≈′-refl = NI.refl
lemma-Fresp (≤′-trans-cong p q) = lemma-Fresp p NI.ⓘₕ lemma-Fresp q
lemma-Fresp (≈′-trans p q) = NI.trans (lemma-Fresp p) (lemma-Fresp q)
lemma-Fresp (≈′-sym p) = NI.sym (lemma-Fresp p)

-- The chain ... → 𝕄ℝ𝕊ₒ 2 → 𝕄ℝ𝕊ₒ 1 → 𝕄ℝ𝕊ₒ 0 as ℕ^op → Cats.
MRS-chain : Functor (Category.op pℕ) (Cats (o ⊔ ℓ ⊔ e) (o ⊔ ℓ ⊔ e) e)
MRS-chain = record
  { F₀ = 𝕄ℝ𝕊ₒ
  ; F₁ = λ {n} {m} m≤′n → downF m≤′n
  ; identity = λ { {n} → lemma-id {n} }
  ; homomorphism = λ { {f = f} {g = g} → lemma-homomorphism f g }
  ; F-resp-≈ = lemma-Fresp
  }

open import Categories.Diagram.Limit MRS-chain renaming (Limit to MRS-Limit)

-- Limit of MRS-chain.
-- MRS∞: the limit object (the "∞-level" MRS category).
MRS∞ = MRS-Limit.apex
-- MRS∞-proj: projection functors MRS∞ → 𝕄ℝ𝕊ₒ n.
MRS∞-proj = MRS-Limit.proj
-- MRS∞-commute: universal property of the limit.
MRS∞-commute = MRS-Limit.limit-commute

-- Objects of a chosen inverse limit.  A limit witness does not determine a
-- canonical object; an MRS∞-Obj must be supplied separately.
MRS∞-Obj : MRS-Limit → Set (o ⊔ ℓ ⊔ e)
MRS∞-Obj L = Category.Obj (MRS∞ L)

-- The finite-stage component of an object of the inverse limit.
MRS∞-at : ∀ {L : MRS-Limit} → MRS∞-Obj L → (n : ℕ) → Category.Obj (𝕄ℝ𝕊ₒ n)
MRS∞-at {L} X∞ n = Functor.F₀ (MRS∞-proj L n) X∞
